name = input("Enter your name here: ")
opponents_name1 = "Abraham"
opponents_name2 = "Arees"
opponents_name3 = "Ishaan"
opponents_name4 = "Brandon"
your_total = input("Enter total here: ")
opponents_total = input("Enter total here: ")
overall = your_total + opponents_total


print(" ")
print(" ")
print (f"{name}'s results: ")
print(" ")
print(" ")
print("Game #1: ")
print(f"Opponents Name: {opponents_name1}")
print("Your points: 19 ")
print("Opponents Points: 17 ")
print(f"Who won game 1: {name}")
print(" ")
print(" ")
print("Game #2: ")
print(f"Opponents Name: {opponents_name2}")
print("Your points: 13 ")
print("Opponents Points: 23 ")
print(f"Who won game 2: {opponents_name2} ")
print(" ")
print(" ")
print("Game #3: ")
print(f"Opponents Name: {opponents_name3}")
print("Your points: 16 ")
print("Opponents Points: 20 ")
print(f"Who won game 3: {opponents_name3}")
print(" ")
print(" ")
print("Game #4: ")
print(f"Opponents Name: {opponents_name4}")
print("Your points: 18 ")
print("Opponents Points: 18 ")
print("Who won game 4: Tie ")
print(" ")
print(" ")
print("Dots and Boxes Table Tracker:")
print(" ")
print(f"Player Name: {name}")

print("")
print("")
print("")
print("")
print("")
print("")
print(" ")
print("Summary: ")
print(" ")
print(f"Your Total Points: {your_total}")
print(f"Total Opponent Points: {opponents_total}")
print(f"Total Points: {overall}")