total_washrooms = str(input("Enter total washrooms here: "))
total_classrooms = str(input("Enter total classes here: "))
total_fountains = str(input("Enter total fountains here: "))
fountain_quality = str(input("Enter avg fountain quality here: "))
clean_washrooms = str(input("Are the washrooms clean kind sir??? : "))
location = str(input("Enter your location here: "))
bvg = str(input("is bvg a good school? : "))


print("Welcome to the school data collection!")
print(" ")
print("Here we total up all the things we have analyzed!")
print(" ")
print("**Location: Bayview Glen**")
print(" ")
print("**Data Collected**")
print(" ")
print("washroom data: ")
print(" ")
print(f"total washrooms found: {total_washrooms}.")
print(" ")
print("classroom data: ")
print(" ")
print(f"total classrooms noted: {total_classrooms}.")
print(" ")
print("fountain data: ")
print(" ")
print(f"total fountains found: {total_fountains}.")
print(" ")
print("fountain quality: ")
print(" ")
print(f"is the fountain quality good?: {fountain_quality}.")
print(" ")
print("washroom cleaning quality: ")
print(" ")
print(f"are the washrooms clean?: {clean_washrooms}.")
print(" ")
print("your location: ")
print(" ")
print(f"you are at: {location}.")
print(" ")
print("bvg: ")
print(" ")
print(f"is bvg a good school? you answered: {bvg}.")