print("Presentation: Huron-Wendat Heritage Minute")
print("Aspect of the Wendat Nation")
print("Traditional Practice")
print("Art and Craftmanship")
print("Language and Storytelling")
print("community traditions")
print("time: 1 minute")
print("date: november 11th, 3032")
print("credits: huron-wendat people!!!!!!")